<template>
  <pub-radio
    v-model="colorPicked"
    name="color"
    label="Red"
    value="red"
    color="red"
  />
  <pub-radio
    v-model="colorPicked"
    name="color"
    label="Green"
    value="green"
    color="green"
  />
  <pub-radio
    v-model="colorPicked"
    name="color"
    label="Blue"
    value="blue"
    color="blue"
  />
  <pub-radio
    v-model="colorPicked"
    name="color"
    label="Yellow"
    value="yellow"
    color="yellow"
  />
  <pub-radio
    v-model="colorPicked"
    name="color"
    label="Pink"
    value="pink"
    color="pink"
  />
  <pub-radio
    v-model="colorPicked"
    name="color"
    label="Cyan"
    value="cyan"
    color="cyan"
  />
  <pub-radio
    v-model="colorPicked"
    name="color"
    label="Purple"
    value="purple"
    color="purple"
  />
  <pub-radio
    v-model="colorPicked"
    name="color"
    label="Black"
    value="black"
    color="black"
  />
  <pub-radio
    v-model="colorPicked"
    name="color"
    label="Grey"
    value="grey"
    color="grey"
  />
</template>

<script lang="ts" setup>
import { ref } from 'vue'
import { PubRadio } from 'vuelicity'

const colorPicked = ref('red')
</script>
